# Generated by Django 5.1.3 on 2026-05-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        ("organizations", "0003_rename_invitation_organizationinvitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="organizations.organization",
            ),
        ),
    ]
