# Generated by Django 5.1.3 on 2026-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("join_request", "Join Request"),
                    ("join_request_approved", "Join Request Approved"),
                    ("join_request_denied", "Join Request Denied"),
                    ("invitation", "Invitation"),
                    ("goal_created", "Goal Created"),
                ],
                max_length=50,
            ),
        ),
    ]
