# Generated by Django 5.1.3 on 2026-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("join_request", "Join Request"),
                    ("join_request_approved", "Join Request Approved"),
                    ("join_request_denied", "Join Request Denied"),
                    ("invitation", "Invitation"),
                    ("goal_created", "Goal Created"),
                    ("goal_updated", "Goal Updated"),
                    ("goal_completed", "Goal Completed"),
                    ("goal_due_soon", "Goal Due Soon"),
                    ("task_created", "Task Created"),
                    ("task_updated", "Task Updated"),
                    ("task_deleted", "Task Deleted"),
                    ("task_due_soon", "Task Due Soon"),
                    ("task_assigned", "Task Assigned"),
                    ("task_overdue", "Task Overdue"),
                    ("task_completed", "Task Completed"),
                ],
                max_length=50,
            ),
        ),
    ]
