# Generated by Django 5.2.14 on 2026-06-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("join_request", "Join Request"),
                    ("join_request_approved", "Join Request Approved"),
                    ("join_request_denied", "Join Request Denied"),
                    ("invitation", "Invitation"),
                    ("goal_created", "Goal Created"),
                    ("goal_updated", "Goal Updated"),
                    ("goal_completed", "Goal Completed"),
                    ("goal_due_soon", "Goal Due Soon"),
                    ("task_created", "Task Created"),
                    ("task_updated", "Task Updated"),
                    ("task_deleted", "Task Deleted"),
                    ("task_due_soon", "Task Due Soon"),
                    ("task_assigned", "Task Assigned"),
                    ("task_overdue", "Task Overdue"),
                    ("task_completed", "Task Completed"),
                    ("task_rescheduled", "Task Rescheduled"),
                    ("task_delayed", "Task Delayed"),
                    ("task_queued", "Task Queued"),
                    ("task_scheduled_from_queue", "Task Scheduled from Queue"),
                    ("task_status_changed", "Task Status Changed"),
                    ("extension_requested", "Extension Requested"),
                    ("extension_approved", "Extension Approved"),
                    ("extension_rejected", "Extension Rejected"),
                    ("chat_message", "New Chat Message"),
                    ("chat_mention", "Mentioned in Chat"),
                    ("chat_group_added", "Added to Group Chat"),
                ],
                max_length=50,
            ),
        ),
    ]
