# Generated by Django 5.1.3 on 2026-05-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_messageattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="url_preview",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
