# Generated by Django 5.1.3 on 2026-06-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message_url_preview"),
        ("goals", "0004_alter_goals_sharing_option_and_more"),
        ("tasks", "0015_tasksubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="goal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="goals.goals",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Message"),
                    ("group", "Group Chat"),
                    ("goal", "Goal Chat"),
                    ("task", "Task Chat"),
                ],
                max_length=10,
            ),
        ),
    ]
