# Generated by Django 5.1.3 on 2026-05-18 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_alter_joinrequest_requested_role_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Rename models safely to preserve DB tables and existing tenant data!
        migrations.RenameModel(
            old_name="Invitation",
            new_name="OrganizationInvitation",
        ),
        migrations.RenameModel(
            old_name="JoinRequest",
            new_name="OrganizationJoinRequest",
        ),
        migrations.RenameModel(
            old_name="Membership",
            new_name="OrganizationMembership",
        ),

        # 2. Rename field created_at to requested_at on OrganizationJoinRequest
        migrations.RenameField(
            model_name="organizationjoinrequest",
            old_name="created_at",
            new_name="requested_at",
        ),

        # 3. Add owner and is_active to Organization
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # 4. Add invited_by to OrganizationMembership
        migrations.AddField(
            model_name="organizationmembership",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
