# Generated by Django 5.1.3 on 2026-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_rename_invitation_organizationinvitation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationjoinrequest",
            name="requested_role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member"), ("owner", "Owner")],
                default="member",
                max_length=20,
            ),
        ),
    ]
