# Generated by Django 5.1.3 on 2026-05-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_alter_organizationjoinrequest_requested_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvitation",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
