# Generated by Django 5.1.3 on 2026-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_organizationinvitation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="custom_permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
