# Generated by Django 5.2.14 on 2026-06-05 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_organizationmembership_custom_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAMLConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "entity_id",
                    models.CharField(
                        help_text="IdP Entity ID / Issuer URL", max_length=255
                    ),
                ),
                ("sso_url", models.URLField(help_text="Single Sign-On IdP URL")),
                (
                    "x509_certificate",
                    models.TextField(help_text="PEM public key certificate of IdP"),
                ),
                (
                    "logout_url",
                    models.URLField(
                        blank=True, help_text="Optional logout URL", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saml_configs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "saml_configuration",
                "ordering": ["company_name"],
            },
        ),
    ]
