# Generated by Django 5.1.3 on 2026-06-08 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_samlconfiguration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SAMLConfiguration",
        ),
    ]
