# Generated by Django 5.1.3 on 2026-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_delete_samlconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="additional_breaks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of extra breaks, e.g., [{'start': '15:00:00', 'end': '15:15:00'}]",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="lunch_break_end",
            field=models.TimeField(default="14:00:00"),
        ),
        migrations.AddField(
            model_name="organization",
            name="lunch_break_start",
            field=models.TimeField(default="13:00:00"),
        ),
        migrations.AddField(
            model_name="organization",
            name="maximum_scan_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="organization",
            name="tea_break_end",
            field=models.TimeField(default="17:30:00"),
        ),
        migrations.AddField(
            model_name="organization",
            name="tea_break_start",
            field=models.TimeField(default="17:00:00"),
        ),
        migrations.AddField(
            model_name="organization",
            name="timezone",
            field=models.CharField(default="Asia/Kolkata", max_length=50),
        ),
        migrations.AddField(
            model_name="organization",
            name="working_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of working days (0=Monday, 6=Sunday). Default: [0, 1, 2, 3, 4]",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="working_end_time",
            field=models.TimeField(default="19:00:00"),
        ),
        migrations.AddField(
            model_name="organization",
            name="working_start_time",
            field=models.TimeField(default="10:00:00"),
        ),
    ]
