# Generated by Django 5.2.14 on 2026-06-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_templates", "0002_goalfolder_goalitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("document", "Rich Text Document"),
                    ("checklist", "Checklist"),
                    ("task_list", "Sub-Task List"),
                    ("file", "File Upload"),
                    ("link", "URL/Link"),
                    ("task", "Standard Task"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="templateitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("document", "Rich Text Document"),
                    ("checklist", "Checklist"),
                    ("task_list", "Sub-Task List"),
                    ("file", "File Upload"),
                    ("link", "URL/Link"),
                    ("task", "Standard Task"),
                ],
                max_length=20,
            ),
        ),
    ]
