# Generated by Django 5.1.3 on 2026-06-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_templates", "0003_alter_goalitem_item_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefolder",
            name="goal_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
