# Generated by Django 5.1.3 on 2026-05-19 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="watched_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
