# Generated by Django 5.1.3 on 2026-05-20 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_watchers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
    ]
