# Generated by Django 5.1.3 on 2026-05-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="actual_time_spent_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Total actual time spent in minutes"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="due_time",
            field=models.TimeField(
                blank=True,
                help_text="Specific due time for minute-level precision",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total estimated time in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_overdue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_preference",
            field=models.CharField(
                choices=[
                    ("none", "No Reminder"),
                    ("15m", "15 Minutes Before"),
                    ("30m", "30 Minutes Before"),
                    ("1h", "1 Hour Before"),
                    ("2h", "2 Hours Before"),
                    ("1d", "1 Day Before"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
