# Generated by Django 5.1.3 on 2026-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_task_actual_time_spent_minutes_task_due_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="reminder_preference",
            field=models.CharField(
                choices=[
                    ("none", "No Reminder"),
                    ("15m", "15 Minutes Before"),
                    ("30m", "30 Minutes Before"),
                    ("1h", "1 Hour Before"),
                    ("2h", "2 Hours Before"),
                    ("3h", "3 Hours Before"),
                    ("1d", "1 Day Before"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
