# Generated by Django 5.1.3 on 2026-05-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_task_reminder_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="actual_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual time spent in hours",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Custom reminder time in minutes before the due date",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="reminder_preference",
            field=models.CharField(
                choices=[
                    ("none", "No Reminder"),
                    ("15m", "15 Minutes Before"),
                    ("30m", "30 Minutes Before"),
                    ("1h", "1 Hour Before"),
                    ("2h", "2 Hours Before"),
                    ("3h", "3 Hours Before"),
                    ("1d", "1 Day Before"),
                    ("custom", "Custom Reminder"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
