# Generated by Django 5.2.14 on 2026-05-26 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_taskticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="extension_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of extensions granted for this task"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Task is blocked from further work or extensions",
            ),
        ),
        migrations.CreateModel(
            name="TaskExtensionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("more_time", "Need More Time"),
                            ("blocked", "Blocked by Dependency"),
                            ("scope_change", "Scope Change"),
                            ("personal", "Personal / Sick Leave"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_text", models.TextField(blank=True, null=True)),
                (
                    "proposed_date",
                    models.DateTimeField(help_text="The new requested due date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("modified", "Modified & Approved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "manager_comment",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection or modification",
                        null=True,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_taskextensionrequest",
                "ordering": ["-created_at"],
            },
        ),
    ]
