# Generated by Django 5.1.3 on 2026-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_taskfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sharing_option",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("organization", "Entire Organization"),
                    ("specific", "Specific People"),
                ],
                default="specific",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="visibility_type",
            field=models.CharField(
                choices=[
                    ("organization", "Entire Organization"),
                    ("specific", "Specific Users"),
                ],
                default="specific",
                max_length=20,
            ),
        ),
    ]
