# Generated by Django 5.1.3 on 2026-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0013_alter_task_sharing_option_alter_task_visibility_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskticket",
            name="time_spent_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Total minutes spent on this ticket"
            ),
        ),
    ]
