# Generated by Django 5.1.3 on 2026-05-29 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0014_taskticket_time_spent_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Description of the work done."
                    ),
                ),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="task_submissions/"
                    ),
                ),
                (
                    "url_links",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated or newline-separated URLs.",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("all", "All Organization"),
                            ("specific", "Specific People"),
                            ("assignee_admins", "Only Assignee + Owner/Admin"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visible_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="visible_task_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_tasksubmission",
                "ordering": ["-created_at"],
            },
        ),
    ]
