# Generated by Django 5.1.3 on 2026-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0015_tasksubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="impact",
            field=models.PositiveIntegerField(
                default=5, help_text="Impact score of the task (1-10)"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="risk",
            field=models.PositiveIntegerField(
                default=5, help_text="Risk score of the task (1-10)"
            ),
        ),
    ]
