# Generated by Django 5.1.3 on 2026-06-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0016_task_impact_task_risk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="risk",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                help_text="Risk level of the task: low=1, medium=2, high=3",
                max_length=10,
            ),
        ),
    ]
