# Generated by Django 5.1.3 on 2026-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0017_change_risk_to_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="required_assignees",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of required assignees for this task (1 for individual task, > 1 for group task)",
            ),
        ),
    ]
