# Generated by Django 5.1.3 on 2026-06-10 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_assignees_to_assignee(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        # Using a raw query or through model to fetch assignees to avoid issues with apps model state
        # task.assignees is a ManyToManyRelatedManager, which is normally fine in migrations
        # but to be extremely safe:
        first_assignee = task.assignees.first()
        if first_assignee:
            task.assignee = first_assignee
            task.save(update_fields=['assignee'])

def reverse_migrate_assignee_to_assignees(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        if task.assignee:
            task.assignees.add(task.assignee)

class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0018_task_required_assignees"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="The user responsible for this task (single assignee)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_assignees_to_assignee, reverse_migrate_assignee_to_assignees),
        migrations.RemoveField(
            model_name="task",
            name="assignees",
        ),
    ]
