# Generated by Django 5.1.3 on 2026-06-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0019_remove_task_assignees_task_assignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
    ]
