# Generated by Django 5.2.14 on 2026-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0020_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="planned_end",
            field=models.DateTimeField(
                blank=True, help_text="Calculated planned end time", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="planned_start",
            field=models.DateTimeField(
                blank=True, help_text="Calculated planned start time", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="schedule_status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("QUEUED", "Queued"),
                    ("COMPLETED", "Completed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskextensionrequest",
            name="requested_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Extra hours requested",
                max_digits=5,
                null=True,
            ),
        ),
    ]
