# Generated by Django 5.1.3 on 2026-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0021_task_planned_end_task_planned_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_auto_scheduled",
            field=models.BooleanField(
                default=True, help_text="Whether this task was auto-scheduled"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="last_scheduler_run",
            field=models.DateTimeField(
                blank=True,
                help_text="When the scheduler last processed this task",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="queue_position",
            field=models.PositiveIntegerField(
                blank=True, help_text="Position in the Queue Bucket", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="schedule_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for the current schedule status (e.g. no slots)",
                null=True,
            ),
        ),
    ]
