# Generated by Django 5.2.14 on 2026-06-21 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0007_goals_due_date_goals_start_date"),
        ("organizations", "0009_organization_additional_breaks_and_more"),
        ("tasks", "0022_task_is_auto_scheduled_task_last_scheduler_run_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "schedule_status", "planned_start", "planned_end"],
                name="task_sched_lookup_idx",
            ),
        ),
    ]
