# Generated by Django 5.2.14 on 2026-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0023_task_task_sched_lookup_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("paused", "Paused"),
                    ("delayed", "Delayed"),
                    ("in_review", "In Review"),
                    ("testing", "Testing"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("paused", "Paused"),
                    ("delayed", "Delayed"),
                    ("in_review", "In Review"),
                    ("testing", "Testing"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
