# Generated by Django 5.1.3 on 2026-05-18 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_project_tasklist_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklist",
            name="project",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assignee",
        ),
        migrations.RemoveField(
            model_name="task",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_list",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskList",
        ),
    ]
