# Generated by Django 5.1.3 on 2026-05-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goals",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_goals",
                to="goals.goals",
            ),
        ),
        migrations.AddField(
            model_name="goals",
            name="is_shared_externally",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="goals",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_goals",
                to="goals.goals",
            ),
        ),
        migrations.AddField(
            model_name="goals",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("sales_target", "Sales Target"),
                    ("product_launch", "Product Launch"),
                    ("team_okr", "Team OKR"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="goals",
            name="timeframe",
            field=models.CharField(
                choices=[
                    ("quarterly", "Quarterly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("custom", "Custom"),
                ],
                default="quarterly",
                max_length=20,
            ),
        ),
    ]
