# Generated by Django 5.1.3 on 2026-05-21 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0002_goals_depends_on_goals_is_shared_externally_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goals",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_goals", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="goals",
            name="shared_viewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_view_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goals",
            name="sharing_option",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("organization", "Entire Organization"),
                    ("specific", "Specific People"),
                ],
                default="organization",
                max_length=20,
            ),
        ),
    ]
