# Generated by Django 5.1.3 on 2026-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0004_alter_goals_sharing_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("sales_target", "Sales Target"),
                    ("product_launch", "Product Launch"),
                    ("team_okr", "Team OKR"),
                    ("custom", "Custom Template"),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
