# Generated by Django 5.1.3 on 2026-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0005_alter_goals_template_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goals",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="goals",
            name="start_date",
        ),
        migrations.AlterField(
            model_name="goals",
            name="template_type",
            field=models.CharField(default="none", max_length=50),
        ),
        migrations.AlterField(
            model_name="goals",
            name="timeframe",
            field=models.CharField(default="quarterly", max_length=20),
        ),
    ]
