# Generated by Django 5.2.14 on 2026-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0006_remove_goals_due_date_remove_goals_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goals",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goals",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
