# Generated by Django 5.1.3 on 2026-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
