# Generated by Django 5.1.3 on 2026-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_leaverequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="availability_score",
            field=models.PositiveIntegerField(
                default=100, help_text="Default availability score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_workload_score",
            field=models.PositiveIntegerField(
                default=0, help_text="Default workload score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="efficiency_score",
            field=models.PositiveIntegerField(
                default=80, help_text="Default efficiency score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_score",
            field=models.PositiveIntegerField(
                default=80, help_text="Experience score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="past_performance",
            field=models.PositiveIntegerField(
                default=80, help_text="Past performance score (0-100)"
            ),
        ),
    ]
