# Generated by Django 5.2.14 on 2026-06-22 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_alter_organizationinvitation_status"),
        ("users", "0006_user_availability_score_user_current_workload_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="leave_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="number_of_days",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("Sick", "Sick Leave"),
                    ("Casual", "Casual Leave"),
                    ("Earned", "Earned Leave"),
                    ("WFH", "Work From Home"),
                    ("Half_Day", "Half Day"),
                    ("Comp_Off", "Comp Off"),
                    ("Optional", "Optional Leave"),
                    ("Maternity_Paternity", "Maternity/Paternity Leave"),
                    ("Annual", "Annual Leave"),
                    ("Unpaid", "Unpaid Leave"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Sick", "Sick Leave"),
                            ("Casual", "Casual Leave"),
                            ("Earned", "Earned Leave"),
                            ("WFH", "Work From Home"),
                            ("Half_Day", "Half Day"),
                            ("Comp_Off", "Comp Off"),
                            ("Optional", "Optional Leave"),
                            ("Maternity_Paternity", "Maternity/Paternity Leave"),
                            ("Annual", "Annual Leave"),
                            ("Unpaid", "Unpaid Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                ("total_days", models.FloatField(default=0.0)),
                ("used_days", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_leavebalance",
                "unique_together": {("user", "organization", "leave_type")},
            },
        ),
    ]
