# Generated by Django 5.2.14 on 2026-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_leaverequest_attachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lunch_break_end",
            field=models.TimeField(default="14:00:00"),
        ),
        migrations.AddField(
            model_name="user",
            name="lunch_break_start",
            field=models.TimeField(default="13:00:00"),
        ),
        migrations.AddField(
            model_name="user",
            name="tea_break_end",
            field=models.TimeField(default="17:30:00"),
        ),
        migrations.AddField(
            model_name="user",
            name="tea_break_start",
            field=models.TimeField(default="17:00:00"),
        ),
        migrations.AddField(
            model_name="user",
            name="work_start_time",
            field=models.TimeField(default="10:00:00"),
        ),
    ]
