# Generated by Django 5.2.14 on 2026-06-24 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_lunch_break_end_user_lunch_break_start_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lunch_break_end",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lunch_break_start",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tea_break_end",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tea_break_start",
        ),
        migrations.RemoveField(
            model_name="user",
            name="work_start_time",
        ),
        migrations.CreateModel(
            name="UserWorkingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_start_time", models.TimeField(default="10:00:00")),
                ("work_end_time", models.TimeField(default="18:00:00")),
                ("lunch_break_start", models.TimeField(default="13:00:00")),
                ("lunch_break_end", models.TimeField(default="14:00:00")),
                ("tea_break_start", models.TimeField(default="17:00:00")),
                ("tea_break_end", models.TimeField(default="17:30:00")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_working_schedule",
            },
        ),
    ]
