# Generated by Django 5.2.14 on 2026-06-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_lunch_break_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkingschedule',
            name='work_end_time',
            field=models.TimeField(default='19:00:00'),
        ),
    ]
