# Generated by Django 5.2.14 on 2026-06-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_userworkingschedule_work_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkingschedule",
            name="no_lunch_break",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userworkingschedule",
            name="no_tea_break",
            field=models.BooleanField(default=False),
        ),
    ]
