# Generated by Django 5.1.3 on 2026-06-30 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_userworkingschedule_no_lunch_break_and_more"),
    ]

    operations = []
